// <auto-generated />
using Blazor26.DataAccess.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor26.DataAccess.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor26.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Books"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("Blazor26.Models.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Image = "/Images/Products/smartphone.jpg",
                            Name = "Smartphone",
                            Price = 699.99f,
                            description = "High-end smartphone"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 1,
                            Image = "/Images/Products/laptop.jpg",
                            Name = "Laptop",
                            Price = 1299.99f,
                            description = "Powerful gaming laptop"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 2,
                            Image = "/Images/Products/novel.jpg",
                            Name = "Novel",
                            Price = 19.99f,
                            description = "Interesting fiction novel"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 2,
                            Image = "/Images/Products/biography.jpg",
                            Name = "Biography",
                            Price = 24.99f,
                            description = "Famous person's biography"
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 3,
                            Image = "/Images/Products/tshirt.jpg",
                            Name = "T-Shirt",
                            Price = 14.99f,
                            description = "Cotton t-shirt"
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 3,
                            Image = "/Images/Products/jeans.jpg",
                            Name = "Jeans",
                            Price = 49.99f,
                            description = "Denim jeans"
                        });
                });

            modelBuilder.Entity("Blazor26.Models.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<decimal>("SalesAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductID");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MonthName = "January",
                            ProductID = 1,
                            SalesAmount = 10m
                        },
                        new
                        {
                            Id = 2,
                            MonthName = "February",
                            ProductID = 2,
                            SalesAmount = 5m
                        },
                        new
                        {
                            Id = 3,
                            MonthName = "March",
                            ProductID = 3,
                            SalesAmount = 9m
                        },
                        new
                        {
                            Id = 4,
                            MonthName = "April",
                            ProductID = 4,
                            SalesAmount = 5m
                        },
                        new
                        {
                            Id = 5,
                            MonthName = "May",
                            ProductID = 5,
                            SalesAmount = 8m
                        },
                        new
                        {
                            Id = 6,
                            MonthName = "June",
                            ProductID = 6,
                            SalesAmount = 16m
                        });
                });

            modelBuilder.Entity("Blazor26.Models.Models.Product", b =>
                {
                    b.HasOne("Blazor26.Models.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Blazor26.Models.Models.Sales", b =>
                {
                    b.HasOne("Blazor26.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Blazor26.Models.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
